CREATE TABLE fondosmutuos (
    rut            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    dv_rut         VARCHAR2(1 CHAR) CHECK (dv_rut IN ('0','1','2','3','4','5','6','7','8','9','K')),
    entidad        VARCHAR2(150 CHAR),
    administradora VARCHAR2(150 CHAR),
    vigencia       NUMBER(1,0) CHECK (vigencia IN (1,0)),
    CONSTRAINT fondosmutuos_pk PRIMARY KEY (rut)
);

CREATE TABLE series (
    rut                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    dv_rut              VARCHAR2(1 CHAR) CHECK (dv_rut IN ('0','1','2','3','4','5','6','7','8','9','K')),
    serie               VARCHAR2(50 CHAR),
    caracteristica      VARCHAR2(50 CHAR),
    fechaInicio         DATE,
    fechaTermino        DATE,
    valorInicioCuota    NUMBER(38,6),
    continuadoraDeSerie VARCHAR2(50 CHAR),
    CONSTRAINT series_pk PRIMARY KEY (rut, serie),
    CONSTRAINT fk_rut
    FOREIGN KEY (rut)
    REFERENCES fondosmutuos(rut)
);

CREATE TABLE cuotas (
    rut                                                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    dv_rut                                              VARCHAR2(1 CHAR) CHECK (dv_rut IN ('0','1','2','3','4','5','6','7','8','9','K')),
    serie                                               VARCHAR2(50 CHAR),
    fecha                                               DATE,
    numeroCuotasAportadas                               NUMBER(38,6),
    numeroCuotasRescatadas                              NUMBER(38,6),
    numeroCuotasCirculacion                             NUMBER(38,6),
    valorCuota                                          NUMBER(38,6),
    patrimonioNeto                                      NUMBER(38,6),
    activoTotal                                         NUMBER(38,6),
    numeroDeParticipes                                  NUMBER(38,0),
    numeroDeParticipesInst                              NUMBER(38,0),
    fondosPension                                       NUMBER(1,0) CHECK (fondosPension IN (1,0)),
    remuneracionFijaSocAdmin                            NUMBER(38,6),
    remuneracionVariableSocAdmin                        NUMBER(38,6),
    gastosAfectosIVA                                    NUMBER(38,6),
    gastosNoAfectosIVA                                  NUMBER(38,6),
    comisionDeColocacionCobradaAlMomentoDeLaInversion   NUMBER(38,6),
    comisionDeColocacionCobradaAlMomentoDelRescate      NUMBER(38,6),
    factorDeRescate                                     NUMBER(38,6),
    factorDeAjuste                                      NUMBER(38,6),
    CONSTRAINT cuotas_pk PRIMARY KEY (rut, serie, fecha),
    CONSTRAINT fk_rut_serie
    FOREIGN KEY (rut, serie)
    REFERENCES series(rut, serie)
);
