CREATE TABLE fondosmutuos (
    rut            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    dv_rut         VARCHAR2(1 CHAR) CHECK (dv_rut IN ('0','1','2','3','4','5','6','7','8','9','K')),
    entidad        VARCHAR2(150 CHAR),
    administradora VARCHAR2(150 CHAR),
    vigencia       NUMBER(1,0) CHECK (vigencia IN (1,0)),
    CONSTRAINT fondosmutuos_pk PRIMARY KEY (rut)
);

